export const FETCHING_TODOS = 'FETCHING_TODOS';
export const TODO_FETCH_SUCCESS = 'TODO_FETCH_SUCCESS';
export const TODO_FETCH_FAIL = 'TODO_FETCH_FAIL';

export const ADDING_TODO = 'ADDING_TODO';
export const TODO_ADDED = 'TODO_ADDED';
export const TODO_ADD_FAIL = 'TODO_ADD_FAIL';

export const UPDATING_TODO = 'UPDATING_TODO';
export const TODO_UPDATED = 'TODO_UPDATED';
export const TODO_UPDATE_FAIL = 'TODO_UPDATE_FAIL';

export const FETCHING_BUCKET = 'FETCHING_BUCKET';
export const FETCH_BUCKET_SUCCESS = 'FETCH_BUCKET_SUCCESS';
export const FETCH_BUCKET_FAIL = 'FETCH_BUCKET_FAIL';

export const TOGGLE_FORM = 'TOGGLE_FORM';